### ISSUE TITLE
Can't check signature: No public key (to verify binary from releases)

### ISSUE THREAD

**Issue by hatemosphere** [immutability-io/vault-ethereum#29]
GPG public key is missing to verify pre-compiled binary

## Detailed Description
I wanted to make a shortcut and use pre-compiled binary from https://github.com/immutability-io/vault-ethereum/releases instead of compiling it on my own. Also, I wanted to use the same way of binary verification as Vault has. And in the end, I realized that I have no idea where to find the public part of RSA key with id 3732F74976B99AEC to execute something like:
```bash
gpg --batch --verify SHA256SUMS.sig SHA256SUMS
```
I guess that's because you're using Keybase and they have their own proprietary mechanism to fetch that key. Any chances you could publish it to one of the mainstream GPG key servers? (eg.   hkp://p80.pool.sks-keyservers.net:80, hkp://keyserver.ubuntu.com:80, hkp://pgp.mit.edu:80)

Related discussion https://github.com/keybase/keybase-issues/issues/327

**Comment by cypherhat** [comment]
Let me know if this works:

![screen shot 2018-09-18 at 4 37 16 pm](https://user-images.githubusercontent.com/966542/45714995-27dfcb80-bb61-11e8-9976-a5bb425b315d.png)

**Comment by hatemosphere** [comment]
yep, thanks a lot, it works!
