### ISSUE TITLE
Unable to build plugin

### ISSUE THREAD

**Issue by smartaquarius10** [immutability-io/vault-ethereum#49]
I am trying to build plugin on windows machine. But facing certain errors. Can anyone share the compiled exe of this plugin.

**Comment by nicolas-law** [comment]
Could you provide some logs ? What problems did you encounter ?

**Comment by cypherhat** [comment]
Have you tried https://github.com/karalabe/xgo?

**Comment by smartaquarius10** [comment]
### This is the error with Golang

 **github.com/hashicorp/vault/physical**
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\physical\testing.go:12: t.Helper undefined (type testing.TB has no field or method Helper)
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\physical\testing.go:235: t.Helper undefined (type testing.TB has no field or method Helper)
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\physical\testing.go:292: t.Helper undefined (type testing.TB has no field or method Helper)
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\physical\testing.go:371: t.Helper undefined (type testing.TB has no field or method Helper)
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\physical\testing.go:426: t.Helper undefined (type testing.TB has no field or method Helper)
 **github.com/pborman/uuid**
C:\Users\xxxxxxx\go\src\github.com\pborman\uuid\time.go:15: syntax error: unexpected = in type declaration
 **github.com/hashicorp/vault/vendor/golang.org/x/net/http2**
C:\Users\xxxxxxx\go\src\github.com\hashicorp\vault\vendor\golang.org\x\net\http2\server.go:220: s.RegisterOnShutdown undefined (type *http.Server has no field or method RegisterOnShutdown)

### This is the error with xgo
2018/11/29 03:02:30 Failed to check docker installation: exec: "docker": executable file not found in %PATH%.

**Comment by nicolas-law** [comment]
You have to install Docker in order to use xgo.
You should try vault and the plugin on a UNIX container with Docker (IMO).

**Comment by smartaquarius10** [comment]
I have only company laptop and do not have unix environment available. Can you please build it and provide us the link to download it or upload it here only.

Thank you

**Comment by smartaquarius10** [comment]
I am somehow able to build this plugin. But when trying to add and enable the plugin getting this error:

 **could not set plugin, plugin directory is not configured**

**Comment by cypherhat** [comment]
Vault plugins are a bit tricky. You can see an example of how I configure this plugin for MacOS/Linux [here](https://github.com/immutability-io/vault-ethereum/tree/master/helper).

There is also some documentation on Vault plugins [here](https://www.vaultproject.io/docs/plugin/)

**Comment by smartaquarius10** [comment]
Issue resolved. I was trying to push the plugin through stand by vault. We have to perform these steps through vault leader.
