### ISSUE TITLE
Error while enabling secrets

### ISSUE THREAD

**Issue by smartaquarius10** [immutability-io/vault-ethereum#50]
## Detailed Description
While running this command:

vault secrets enable -path=ethereum -plugin-name=ethereum-plugin plugin

Getting this error:

**[ERR] plugin: plugin acceptAndServe error: strconv.Parselnt: parsing ““: invalid syntax
[ERROR] sys: mount failed: path=ethereum/ error=rpc error: code = Unknown desc = timeout waiting for connection info**

Kindly suggest the resolution

**Comment by cypherhat** [comment]
I think this is part of https://github.com/immutability-io/vault-ethereum/issues/49.
