### ISSUE TITLE
Error during building the vault-ethereum plugin

### ISSUE THREAD

**Issue by aoszwald** [immutability-io/vault-ethereum#51]
Detailed Description:
I pulled the latest vault-ethereum plugin and tried to build it without success.
We are using and building it in a docker environment but Im also not able to build it on my host machine. Around October 2018 it just worked fine.
In the docker environment it's uses image FROM golang:1.9

Error:
Step 3/14 : COPY ./vault/ethereum /go/src/github.com/immutability-io/vault-ethereum
 ---> 2b45f96ebb53
Step 4/14 : WORKDIR /go/src/github.com/immutability-io/vault-ethereum
Removing intermediate container b038a1e526ed
 ---> 3ad2a13dd564
Step 5/14 : RUN go get ./
 ---> Running in 229f06c45279
package github.com/ethereum/go-ethereum/crypto/sha3: cannot find package "github.com/ethereum/go-ethereum/crypto/sha3" in any of:
	/usr/local/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOROOT)
	/go/src/github.com/ethereum/go-ethereum/crypto/sha3 (from $GOPATH)
ERROR: Service 'vault' failed to build: The command '/bin/sh -c go get ./' returned a non-zero code: 1

Environment:
OS: Mac OS Mojave 10.14.2 (18C54)
Docker version: Version 18.03.1-ce-mac65 (24312)
GO version: go version go1.11.1 darwin/amd64
vault-ethereum: latest

**Comment by cypherhat** [comment]
Seems that go-ethereum made some changes. Let me realign:

```
 rename {crypto => vendor/golang.org/x/crypto}/sha3/doc.go (96%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/hashes.go (58%)
 create mode 100644 vendor/golang.org/x/crypto/sha3/hashes_generic.go
 rename {crypto => vendor/golang.org/x/crypto}/sha3/keccakf.go (100%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/keccakf_amd64.go (88%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/keccakf_amd64.s (100%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/register.go (100%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/sha3.go (100%)
 create mode 100644 vendor/golang.org/x/crypto/sha3/sha3_s390x.go
 create mode 100644 vendor/golang.org/x/crypto/sha3/sha3_s390x.s
 rename {crypto => vendor/golang.org/x/crypto}/sha3/shake.go (83%)
 create mode 100644 vendor/golang.org/x/crypto/sha3/shake_generic.go
 rename {crypto => vendor/golang.org/x/crypto}/sha3/xor.go (100%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/xor_generic.go (100%)
 rename {crypto => vendor/golang.org/x/crypto}/sha3/xor_unaligned.go (100%)
```

**Comment by richard-mauri** [comment]
Maybe this project should use a dependency manager tool like https://github.com/golang/go/wiki/Modules ?

Would you accept a PR to factor that in?
(I"m new to this project, so it may take a little acclimation forst)

**Comment by cypherhat** [comment]
@richard-mauri I would gladly accept a PR for better dependency management. I was gonna use `govendor` but Vault and Ethereum move so fast. I haven't had a chance to get acclimated to go modules yet, but if you can help, it would be greatly appreciated.

**Comment by miguelmota** [comment]
suggest using [go mod](https://github.com/golang/go/wiki/Modules)

```shell
export GO111MODULE=on
go mod init
go mod vendor
```

will submit pr shortly

**Comment by miguelmota** [comment]
submitted pr https://github.com/immutability-io/vault-ethereum/pull/57 but then realized there's an existing pr https://github.com/immutability-io/vault-ethereum/pull/55

**Comment by richard-mauri** [comment]
I tried to use the new go-coinmarketcap v0.1.0 release tag and the ame compile error happens.
See https://github.com/miguelmota/go-coinmarketcap/issues/4#issuecomment-460649625

**Comment by richard-mauri** [comment]
#55 includes change to use the new API so once that PR is merged this ticket can be closed

**Comment by cypherhat** [comment]
Fixed. https://github.com/immutability-io/vault-ethereum/releases/tag/v0.2.8
