### ISSUE TITLE
Finding Logs for the ethereum plugin

### ISSUE THREAD

**Issue by ppeinsold** [immutability-io/vault-ethereum#58]
Want to see the exceptions/logs that vault is throwing when I use the /debit endpoint.

## Detailed Description

Ethereum plugin returns 500 error when /debit endpoint is used. Strange thing is, that this behaviour is not stable. Sometimes it throws the error sometimes not with same input data. I now want to debug it by first having a look at some log output, but I cannot find any logs.

Can you tell me are there any logs that I can use to debug the problem? 
Thank you in advance!

**Comment by cypherhat** [comment]
Logs end up where you have Vault configured to log.

**Comment by ppeinsold** [comment]
Alright, do you know where this setting is made?

**Comment by cypherhat** [comment]
[This describes setting the log level](https://www.vaultproject.io/docs/configuration/#log_level).  

If you are running Vault on a Mac, and you start it like this:

```
$ /usr/local/bin/vault server -config /Users/cypherhat/etc/vault.d/vault.hcl > /Users/cypherhat/etc/vault.d/logs/errors.log &
```

Then your error logs will be in `/Users/cypherhat/etc/vault.d/logs/errors.log`.

[Audit logs are configured differently](https://www.vaultproject.io/docs/audit/index.html).
