### ISSUE TITLE
Error in path_blocks.go

### ISSUE THREAD

**Issue by suchal** [immutability-io/vault-ethereum#60]
## Context
![image](https://user-images.githubusercontent.com/21312386/55931013-4d3b4080-5c3d-11e9-93a3-e7b2e29da33a.png)

## Possible Implementation
remove the .Unit64() from line 92
![image](https://user-images.githubusercontent.com/21312386/55931033-5cba8980-5c3d-11e9-8511-ace0f62becad.png)

**Comment by cypherhat** [comment]
Fixed https://github.com/immutability-io/vault-ethereum/releases/tag/v0.2.8
